sudo: required
language: python
cache: pip

python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  
  # PyPy versions
  - "pypy3.5"
  - "pypy3.6"
  - "pypy3.7"
  - "pypy3.8"

  - "nightly"
  
install:
  - pip install mypy
  - pip install .

script:
  - mypy -m configs
  - cd example && chmod +x run_tests.sh && ./run_tests.sh
