sudo: required
language: python
cache: pip

dist: trusty

python:
  - "3.6"
  - "pypy3"
  - "nightly"

install:
  # On nightly, upgrade setuptools first to work around
  # https://github.com/pypa/setuptools/issues/1257
  - if [[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then travis_retry pip install -U setuptools; fi
  - pip install mypy
  - pip install .

script:
  - mypy -m configs
  - cd example && chmod +x run_tests.sh && ./run_tests.sh

notifications:
  email:
    on_failure: change
    on_success: never